using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    public CharacterController2D controller;

    public float speed = 40f;

    float horizontalMove = 0f;
    bool jump = false;
    bool Crouch = false;

    // Update is called once per frame
    void Update()
    {
        horizontalMove = Input.GetAxisRaw("Horizontal")* speed;

        if (Input.GetButtonDown("Jump"))
        {
            jump = true;
        }

        if(Input.GetButtonDown("Crouch"))
        {
            Crouch = true;

        }else if (Input.GetButtonUp("Crouch"))
        {
            Crouch = false;
        }
    }

    void FixedUpdate()
    {
        controller.Move(horizontalMove *Time.fixedDeltaTime, Crouch, jump);
        jump = false;
    }
}
